name: test image

on:
  pull_request:
    paths:
      - gfts-track-reconstruction/jupyterhub/images/**

defaults:
  run:
    working-directory: gfts-track-reconstruction/jupyterhub

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          pip install --upgrade setuptools pip
          pip install --upgrade -r requirements.txt

      - name: Build image with chartpress
        run: |
          python3 deploy.py chartpress --no-push
